spring:
  flyway:
    enabled: true
    schemas: data_cheque
  application:
    name: data_cheque
  main:
    web-application-type: servlet
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    name: data_cheque
    username: postgres
    password: 566031
    url: jdbc:postgresql://localhost:5432/data_cheque?currentSchema=data_cheque
    hikari:
      schema: data_cheque

server:
  port: 8080

jwt:
  secret: m38jKz3e+IWgLSgOlHmmfj42jJqpN/Q1470cAzp/UFXp9eZ4o61+CRr/dMsjvE3FNrr9mO0M345zSp+h8KAV3Q==