spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: data_cheque
  application:
    name: data_cheque
  main:
    web-application-type: servlet
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    name: data_cheque
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/data_cheque
    hikari:
      schema: data_cheque

server:
  port: 8080