spring:
  application:
    name: data_cheque
  main:
    web-application-type: servlet
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    name: data_cheque
    username: postgres
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/data_cheque
    hikari:
      schema: data_cheque

server:
  port: 8080