CREATE TABLE IF NOT EXISTS data-cheque.empregador (
    id UUID PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    cnpj VARCHAR(14) NOT NULL UNIQUE,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL UNIQUE,
    contador_UUID VARCHAR NOT NULL,
    FOREIGN KEY (contador_UUID) REFERENCES contador (UUID)
)